# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
#     - uses: actions/checkout@v2
#     - name: Push to Heroku
#       uses: actions/setup-node@v2
#       with:
#         node-version: 16
#         cache: 'npm'
#         heroku_api_key: ${{ secrets.HEROKU_TOKEN }}
#         heroku_app_name: ${{ secrets.HEROKU_APP }}#Must be unique in Heroku
#         heroku_email: ${{ secrets.HEROKU_EMAIL }}        
#         procfile: "web: npm start"
     
#     - name: Create Pull Request
#       id: cpr
#       uses: peter-evans/create-pull-request@v3
    - name: Create Pull Request with cli 
      run: |
       gh  pr create -t  "Sample tile " -b "sample body" 
      
     
#      #### create pull request
#     - name: Create Pull Request
#       uses: peter-evans/create-pull-request@v3
#       with:
#         token: ${{ secrets.PAT }}
#         commit-message: Add report file
#         title: '[Example] Add report file'
#         body: >
#           This PR is auto-generated by 
#           [create-pull-request](https://github.com/peter-evans/create-pull-request).

     
#      - uses: actions/checkout@v3

#       # Make changes to pull request here
#     - uses: actions/checkout@v3
#     - name: Create Pull Request
# #       uses: mohantechnology/www
# #     - name: Create Pull Request
#       uses: mohantechnology/www@v4
#       with:
#         commit-message: updated app 
#         title: Update Changelog
# #         body: please preview the app at https://${{ secrets.HEROKU_APP }}.herokuapp.com  
#         body:  sample body
#         branch: update-changelog
#         base: main
# # buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
   
